FRONTENDBOOTCAMP-13th/JS-01-c1ass

- index.html
> :sparkles: feat: index.html에 컴포넌트/페이지 링크 연결

- src/components/clock-widget.html
> :sparkles: feat: clock-widget에 그림자 추가

- index.html
- src/components/icon-bar.html
- src/main.ts
> feature: icon-bar 컴포넌트 구현 

- src/components/calendar-widget.html
- src/ts/calendar-widget.ts
- calendar-widget 마크업, 스타일
- calendar-widget 날짜 기능 구현
resolves #5
> feat: Calendar-widget 컴포넌트 구현

- index.html
- src/components/top-bar.html
- src/ts/top-bar.ts
- top-bar 컴포넌트 구현
- top-bar 이미지 추가 public/assets/top-bar
resolves #21
> :sparkles: feat:top-bar 컴포넌트 구현

- src/ts/mac-panel-container.ts
> :sparkles: feat: full screen이 될 때와 default screen이 될 때 transiton 구현

- src/ts/calendar-widget.ts
- calendar-widget: setInterval로 날짜 갱신 => setTimeout 사용하여 수정
resolves #46
> calendar-widget에서 setTimeout으로 날짜 갱신 문제 수정 (테스트 미완료)

- src/pages/card.html
- src/ts/card.ts
- 뽑은 카드에 tab키로 접근 안되던 문제 수정
- 컬렉션 보기 클릭시 html을 랜더링 하는 방식에서 hidden 클래스를 토글하는 방식으로 수정
resolves #53
> :bug: fix: card 게임 접근성 문제, 컬렉션 모달 이미지 깜빡임 문제 수정

- index.html
- src/components/clock-widget.html
- src/components/icon-bar.html
- src/components/icon.html
- src/components/top-bar.html
- src/components/weather-widget.html
- src/pages/card.html
- src/pages/mac.html
> :lion: chore: html 파일의 head에 폰트 추가

- src/pages/mac.html
- src/style.css
- src/ts/widget-move.ts
> :sparkles: feat: 위젯 드래그앤드롭 기능 구현

- src/ts/clock-widget.ts
> :bug: fix: clock-widget 바늘 움직이는 로직을 변경해서 위젯을 움직일 때 바늘이 멈추는 현상 수정

- src/programID.ts
> :bug: fix: doodi의 fileURL 변경

- src/style.css
- src/ts/mac-panel-container.ts
> :bug: fix: iframe 클릭 시 mac-panel이 최상단에 배치되지 않은 현상을 투명한 mac-panel-cover를 구현해서 수정

- src/ts/doodi-game/doodi-screen.ts
- src/ts/doodi-game/doodi-timer.ts
- doodi-game 중복 함수 제거
- doodi-game 리플레이 시 타이머바 초기화 오류 수정
resolves #78
> Refactor/doodi game 오류 수정

- src/pages/doodi-all.html
- src/ts/doodi-game/doodi-mole.ts
- src/ts/doodi-game/doodi-screen.ts
- src/ts/doodi-game/doodi-timer.ts
- doodi-game 영상을 배속 영상으로 교체, 미사용 함수 제거
- doodi-game 불필요한 콘솔 제거
resolves #90
> Refactor/doodi game 영상 교체 및 콘솔 제거

- src/pages/arrow-dodge-game.html
- src/ts/arrow-dodge-game.ts
> :bug: fix: 불필요한 콘솔 로그 제거

- src/pages/card.html
- src/ts/card.ts
- 로딩 화면 구현
- 이미지가 미리 불러와지도록 수정
resolves #96
> :bug: fix: card게임 - 이미지가 미리 불러와지도록 수정

- src/pages/doodi-all.html
- src/ts/doodi-game/doodi-load.ts
doodi-game 로딩화면 구현 및 이미지 프리로드 함수 테스트
resolves #95
> :white_check_mark: test: doodi-game 로딩화면 구현 및 이미지 프리로드 함수 테스트

- src/pages/mac.html
> :lion: chore: mac-bg 복원

- src/pages/doodi-all.html
- src/ts/doodi-game/doodi-animation.ts
- src/ts/doodi-game/doodi-mole.ts
- src/ts/doodi-game/doodi-screen.ts
- doodi-game 효과음 재사용하도록 수정
- doodi-game 커서 이미지 오류 위해 커서 이미지 재사용으로 수정
- doodi-game 커서 이미지 더블클릭 접근 못하도록 수정
- doodi-game 반응형으로 수정
resolves #100
> Refactor/doodi game 반응형으로 수정

- index.html
- src/components/context-menu.html
- src/style.css
- vite.config.js
> :sparkles: feat: context-menu UI 구현

- src/components/top-bar.html
- src/pages/mac.html
> :sparkles: feat: top-bar 사용자의 다크/라이트 모드에 반응하게 구현

- package-lock.json
- package.json
- src/pages/mac.html
- src/ts/icon-move.ts
- [] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).
- `package.json`에 `sortablejs` 가 추가되었습니다.
- `npm i` 해야 합니다.
resolves #125
> :sparkles: feat: sortableJS library를 사용하여 아이콘을 드래그&드롭으로 위치를 조정하는 기능 구현

- src/pages/doodi-all.html
- src/ts/doodi-game/doodi-load.ts
- src/ts/doodi-game/doodi-mole.ts
> Chore/doodi game - 두더지 크기 수정

- src/pages/mac.html
- src/pages/socks-game.html
- src/ts/doodi-game/doodi-load.ts
- src/ts/socks-game.ts
- 이미지 프리로드 수정 (+socks-game)
- mac 충돌 수정
resolves #137
> Bugfix/doodi game - 이미지 프리로드 수정 (+socks-game), mac 충돌 수정

- public/asserts/mac/add-icon.svg
- src/ts/icon-bar.ts
- src/ts/mac-setting.ts
> :sparkles: feat: icon을 추가하는 icon을 icon-bar에 추가

- src/ts/button-mode-change.ts
- mac 색 모드 변경 애니메이션 추가
resolves #150
> :lion: chore: mac 색 모드 변경 애니메이션 추가

- src/ts/context-menu.ts
> :sparkles: feat: context-menu의 클릭이벤트가 동작하도록 mouseup event로 기능 구현

- src/ts/widget-manager.ts
> :sparkles: feat:  타이머 기능 구현

- src/ts/widget-manager.ts
> :lipstick: style: 타이머 사이즈 수정

- src/programID.ts
- src/style.css
- src/ts/add-icon-setting.ts
- src/ts/icon-bar.ts
- src/ts/mac-panel-container.ts
> :sparkles: feat: add-icon 버튼을 클릭하면 icon이 추가되는 기능 구현

- src/style.css
> :bug: fix: widget에 마우스를 올렸다가 뺐을 때 부자연스러운 현상 수정

- src/ts/mac-setting.ts
> :white_check_mark: test: dev에서만 필요한 버튼 추가하는 코드 비활성화

- index.html
- src/ts/context-menu.ts
> :lion: chore: index.html의 마크업을 mac.html로 교체

- src/components/calendar-widget.html
- src/components/mac-panel.html
- src/components/memo-widget.html
> :lion: chore: lang 변경 작업

- index.html
- src/pages/mac.html
- src/ts/mac-setting.ts
> :lipstick: style: 포스트잇 위치, 애니메이션 수정

- src/pages/presentation.html
- src/ts/mac-panel-container.ts
- src/ts/widget-manager.ts
- vite.config.js
> :sparkles: feat: 발표 자료 준비
